on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_profilejson:
    name: Validate edited profile.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate profile.json schema
        run: |
          for file in $(find . -name 'profile.json' | grep -v '_template/'); do
            if ! jsonschema -i "$file" ./profile.schema.json; then
              exit 1
            fi
          done
